spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vetCare
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
logging:
  level:
    org:
      hibernate:
        SQL: debug


server:
  port: 8081
jwt:
  secret: ${JWT_SECRET:cambia_esto_en_produccion_por_variable_de_entorno}
  expiration: 14400000
